version: '3.7'

services:

  teamcity:
    image: 'jetbrains/teamcity-server'
    volumes:
      - './docker/datadir:/data/teamcity_server/datadir'
      - './docker/logs:/opt/teamcity/logs'
    ports:
      - '80:8111'
    depends_on:
      - database

  database:
    image: mysql:5.7
    volumes:
    - ./docker/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
