version: '3.7'

services:

  teamcity-server:
    image: jetbrains/teamcity-server:2018.1.2
    volumes:
      - ./docker/datadir:/data/teamcity_server/datadir
      - ./docker/logs:/opt/teamcity/logs
    ports:
      - 80:8111

  teamcity-agent:
    image: jetbrains/teamcity-agent:2018.1.2
    environment:
      SERVER_URL: http://teamcity-server
